LyricsAPI/Models/ArtistConfirmViewModel.cs
using System.Collections.Generic;

namespace LyricsAPI.Models
{
    public class ArtistConfirmViewModel
    {
        public ArtistConfirmViewModel()
        {
            Artists = new List<ArtistViewModel>();
        }

        public string ArtistSearchName { get; set; }
        public string ValidationMessage { get; set; }
        public List<ArtistViewModel> Artists { get; set; }
        public string SelectedArtistId { get; set; }
    }
}

LyricsAPI/Models/ArtistSelectViewModel.cs
using System.ComponentModel;
using System.Runtime.Serialization;

namespace LyricsAPI.Models
{
    public class ArtistSelectViewModel
    {               
        [DisplayName("Artist Name")]
        public string ArtistName { get; set; }
        public string ValidationMessage { get; set; }
    }
}

LyricsAPI/Models/ArtistViewModel.cs
namespace LyricsAPI.Models
{
    public class ArtistViewModel
    {
        public string Id { get; set; }

        public string Name { get; set; }

        public string Country { get; set; }
    }
}

LyricsAPI/Models/ErrorViewModel.cs
namespace LyricsAPI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LyricsAPI/Models/RecordingViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LyricsAPI.Models
{
    public class RecordingViewModel
    {
        public string Id { get; set; }
        public string Title { get; set; }
    }
}

LyricsAPI/Models/RecordingsViewModel.cs
using System.Collections.Generic;

namespace LyricsAPI.Models
{
    public class RecordingsViewModel
    {
        public string ArtistId { get; set; }
        public string ArtistName { get; set; }
        public List<RecordingViewModel> Recordings { get; set; }
      
        public int? AverageWordCount { get; set; }
    }
}

LyricsAPI/Controllers/ArtistController.cs
using LyricsAPI.Interfaces;
using LyricsAPI.Models;
using Microsoft.AspNetCore.Mvc;

namespace LyricsAPI.Controllers
{
    public class ArtistController : Controller
    {
        private readonly IArtistService _artistService;
        private readonly ILyricsService _lyricsService;

        public ArtistController(IArtistService artistService, ILyricsService lyricsService)
        {
            _artistService = artistService;
            _lyricsService = lyricsService;
        }

        public IActionResult Index()
        {
            var artistSelectViewModel = new ArtistSelectViewModel();
            return View(artistSelectViewModel);
        }

        [HttpPost]
        public IActionResult Index(ArtistSelectViewModel artistSelectViewModel)
        {
            artistSelectViewModel.ValidationMessage = "";

            if (string.IsNullOrEmpty(artistSelectViewModel.ArtistName))
            {
                artistSelectViewModel.ValidationMessage = "Please confirm the artist name";
                return View("Index", artistSelectViewModel);
            }

            var artists = _artistService.GetByName(artistSelectViewModel.ArtistName).Result;
            var artistConfirmViewModel = new ArtistConfirmViewModel
            {
                ArtistSearchName = artistSelectViewModel.ArtistName
            };

            foreach (var artist in artists)
            {
                artistConfirmViewModel.Artists.Add(new ArtistViewModel
                {
                    Id = artist.Id,
                    Name = artist.Name + " (" + artist.Country + ")"
                });
            }
      
            return View("Confirm", artistConfirmViewModel);
        }

        [HttpPost]
        public IActionResult Confirm(ArtistConfirmViewModel artistConfirmViewModel)
        {
            artistConfirmViewModel.ValidationMessage = "";

            if (string.IsNullOrEmpty(artistConfirmViewModel.SelectedArtistId)) 
            {
                artistConfirmViewModel.ValidationMessage = "Please confirm the artist name";
                return View(artistConfirmViewModel);
            }

            string selectedArtistName = "";
            foreach(var artist in artistConfirmViewModel.Artists)
            {
                if (artist.Id == artistConfirmViewModel.SelectedArtistId)
                {
                    selectedArtistName = artist.Name;
                    break;
                }
            }

            var recordingsViewModel = _lyricsService.GetRecordingsByArtistId(artistConfirmViewModel.SelectedArtistId, 
                selectedArtistName).Result;
       
            return View("ShowRecordingsSummary", recordingsViewModel);
        }

        public IActionResult ShowLyricSummary(RecordingsViewModel lyricsViewModel)
        {
            return View(lyricsViewModel);
        }
    }
}

LyricsAPI/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using LyricsAPI.Models;

namespace LyricsAPI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LyricsAPI/Views/Artist/Confirm.cshtml
@model LyricsAPI.Models.ArtistConfirmViewModel

@{
    ViewData["Title"] = "Artist Lookup";
}

<div class="text-center">
    <h1 class="display-4">Artist Confirmation</h1>

    @using (Html.BeginForm("Confirm", "Artist", FormMethod.Post))
    {
        <div class="form-group">
            <h4>Artists Found For: @Html.DisplayFor(m => m.ArtistSearchName)</h4>

            @Html.DropDownListFor(m => m.SelectedArtistId, new SelectList(Model.Artists, "Id", "Name", "SelectedArtist"))
            <br><br>
            @Html.ValueFor(m => Model.ValidationMessage)

            @Html.HiddenFor(m => m.ArtistSearchName)
            @Html.HiddenFor(m => m.ValidationMessage)
            @Html.HiddenFor(m => m.SelectedArtistId)
            @for (int i = 0; i < Model.Artists.Count; i++)
            {
                @Html.HiddenFor(m => m.Artists[i].Id)
                @Html.HiddenFor(m => m.Artists[i].Name)
            }
            <label>@Model.ValidationMessage</label>
        </div>
        <div class="form-group">
            <input type="submit" value="Confirm Artist" class="btn btn-primary" />
        </div>
    }
</div>

LyricsAPI/Views/Artist/Index.cshtml
@model ArtistSelectViewModel

@{
    ViewData["Title"] = "Artist Lookup";
}

<div class="text-center">
    <h1 class="display-4">Results</h1>
    <p>Lyrics API Caller</p>
</div>

<div class="text-center">
    <form asp-action="Index" method="post" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <table>
                <tr>
                    <td>
                        <label asp-for="ArtistName" class="control-label"></label>
                    </td>
                    <td>
                        <input asp-for="ArtistName" class="form-control" />
                    </td>
                    <td>
                        <input type="submit" value="Search" class="btn btn-primary" />
                    </td>
                </tr>
            </table>
            <label>@Model.ValidationMessage</label>
        </div>
    </form>
</div>

LyricsAPI/Views/Artist/ShowRecordingsSummary.cshtml
@model LyricsAPI.Models.RecordingsViewModel

@{
    ViewData["Title"] = "Artist Lookup";
}

<div class="text-center">
    <h1 class="display-4">Recordings for @Model.ArtistName</h1>
    <p>Lyrics API Caller</p>
</div>

<div class="text-center">
    <form asp-action="Results" method="post" enctype="multipart/form-data">
        <div class="form-group">
            <h4>There are @Model.Recordings.Count recordings available in the database:</h4>
            <br><br>
                <table>
                    @foreach (var recording in Model.Recordings)
                    {
                        <tr>
                            <td style="text-align:left;">
                                @recording.Title
                            </td>
                        </tr>
                    }
                </table>
        </div>
    </form>
</div>

LyricsAPI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Lyrics API Caller</p>
</div>

LyricsAPI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LyricsAPI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LyricsAPI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Artist" asp-action="Index">Artist Lookup</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - LyricsAPI
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>